name: getx
description: "A Complete health management application using flutter framework"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  upgrader: ^10.3.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  expandable: ^5.0.1
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  http: ^1.1.0
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  device_info_plus: ^10.1.0
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.0.3
  flutter_local_notifications: ^17.2.1
  firebase_core: ^3.1.1
  firebase_messaging: ^15.0.2
  firebase_crashlytics: ^4.0.2
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.1
  flutter_snake_navigationbar: ^0.6.1
  avatar_glow: ^3.0.1
  dotted_border: ^2.1.0
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  path: ^1.8.3
  fl_chart: ^0.63.0
  pdf: ^3.10.7
  flutter_image_compress: ^2.1.0
  toasty_box: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
