import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      "edit": "Edit",
      "next": "Next",
      "notification": "Notification",
      "language": "Language",
      "select_language": "Select Language",
      "select_prefer_langugae": "Please select your preferred language.",
      "continue": "Continue",
      "loading": "Loading..",
      "error": "Error",
      "server_busy":
      "Server Busy: We apologize for the inconvenience, but our server is currently experiencing a high volume of traffic. Please use our regular sign-up process to create your account. Thank you for your patience.",
      "please_lo_first": "Please Login First!",
      "right_resarve_by": "All rights reserved by",
      "continueText": "Continue",
      "success": "Success",
      //snackbar
      "warning": "Warning",
      //sign up
      "sign_up":"Sign Up",
      "sign_up_slogan":"Enter your name, email and password to get register",
      "name":"Name",
      "email":"Email",
      "phone":"Phone",
      "password":"Password",
      "or_sign_up_with":"or sign up with",
      "agree_term":"I agree to the ",
      "and":"and",
      "already_have_account":"Already have account?",
      "alReserveBy":"All rights reserved by ",
      //sign in
      "sign_in":"Sign In",
      "forgotPassword":"Forgot Password",
      "or_sign_in_with":"or sign in with",
      "dont_have_account":"Don't have account?",
      //home
      "hello": "Hello",
      "im_your_assistant": "I'm your money management assistant",
      "this_week": "This Week",
      "this_month": "This Month",
      "this_year": "This Year",
      "recent_transaction": "Recent Transactions",
      "see_all": "See All",
      "no_transaction_found": "No Transaction Found!",
      //add transaction
      "transactions": "Transactions",
      "add_transaction": "Add Transaction",
      "transaction_details": "Transaction Details",
      "income": "Income",
      "expense": "Expense",
      "saving": "Saving",
      "insufficient_balance":
      "Insufficient Balance. You need to first add income.",
      "available_balance": "Available Balance",
      "transaction_name": "Transaction Name",
      "purpose_of_transaction": "Purpose of Transaction",
      "enter_amount": "Enter Amount",
      "select_date": "Select Date",
      "select_categgory": "Select Category",
      "add_calculate_amount": "Add Calculated Amount",
      "select_a_category": "Select a category",
      "please_enter_amount": "Please Enter Amount of Transaction",
      "enter_transaction_name": "Enter Transaction Name",
      "save": "Save",
      "write_note": "Write Note..",
      //attachment
      "browse_imge_here": "Browse your image",
      "supports": "Supports",
      "choose_method": "Choose your method",
      "max_2_size_allow": "Allowed Maximum image size 2 MB",
      "you_denied_camera": "You Denied camera access",
      //budget
      "your_budget": "Your Budget",
      "active": "Active",
      "closed": "Closed",
      "add_budget": "Add Budget",
      "create_budget": "Create Budget",
      "budget_name": "Budget Name",
      "select_budget_period": "Select Budget Period",
      "start_date": "Start Date",
      "end_date": "End Date",
      "warning_message":
      "You will get a warning when you’ve reached 50%, 80%,90% left of your budget",
      "budget_overspend": "Budget Overspent",
      "budget_overspend_message":
      "You will get a warning when you’ve exceeded 100% of your budget",
      "enter_budget_name": "Please enter budget name!",
      "enter_budget_period": "Please select budget period!",
      "enter_start_date": 'Please choose start date!',
      "enter_end_date": 'Please choose estimated end date!',
      "available_budget": "Available Budget",
      "already_spend": "You already spend",
      "from": "from",
      "recent_expense": "Recent Expense",
      "no_expense_history": "No Expense History",
      "add_new_expense": "Add New Expense",
      "cancel": "Cancel",
      "delete": "Delete",
      "add_record": "Add Record",
      "close_record": "Close Record",
      //report
      "report": "Report",
      "download_pdf": "Download PDF",
      "cash_in": "Cash In",
      "cash_out": "Cash Out",
      "view_all": "View All",
      "title": "Title",
      "date": "Date",
      "amount": "Amount",
      "statistic": "Statistic",
      "total_cash": "Total Cash",
      "total_cash_out": "Total Cash Out",
      "total_save": "Total Save",
      "balance": "Balance",
      "budget": "Budget",
      "filter": "Filter",
      "search": "Search",
      //goal
      "your_goal": "Your Goals",
      "goals": "Goals",
      "are_you_ambitious": "Are you not an ambitious person?",
      "paused": "Paused",
      "reached": "Reached",
      "new_goal": "New Goal",
      "not_found": "Not Found",
      "add_goal": "Add Goal",
      "so_close_your_dream": "So close to your dream goal!",
      "estimate_time_reach_goal": "Estimated time to reach goal",
      "add_money": "Add Money",
      "pause_goal": "Pause Goal",
      "reach_goal": "Reached Goal",
      "recent_added_money": "Recent Added Money",
      "what_do_you_want_this_goal": "What do you want in this goal?",
      "step": "Step",
      "step_1_new_goal_message":
      "Setting a goal is first step towards achiveing it.",
      "goal_title": "Goal Title",
      "select_saving_period": "Select Saving period",
      "select_reminder_period": "Select Reminder Period",
      "expected_maturity_date": "Expected Maturity Date",
      "success_notify": "Success Notify",
      "success_notity_message":
      "You will get a warning when you've reached 50%, 80%, 90%, left of your budget.",
      "goal_overdue": "Goal Overdue",
      "goal_overdue_message":
      "You will get a warning when you didn't save money one time between duration.",
      "preview": "Preview",
      "recheck_your_goal": "Recheck your goal.",
      "previous": "Previous",
      "what_do_you_want_goal": "What do you want in this goal?",
      "step_2_goal_message":
      "Setting a goal is second step towards achiving it.",
      "create_goal": "Create Goal",
      "weekly": "Weekly",
      "monthly": "Monthly",
      "yearly": "Yearly",
      "one_time": "One Time",
      //settings
      "settings": "Settings",
      "settings_more": "Settings & More",
      "general": "General",
      "currency": "Currency",
      "application": "Application",
      "account_delete": "Account Delete",
      "log_out": "Log Out",
      "delete_message":
      "Warning: Account deletion is irreversible.Once deleted, your data connot be recovered. Authority will not be responsible for this loss of data.",
      "fullName": "Full name",
      "email": "Email",
      "dob": "Date of birth",
      "your_reason": "Your reason...",
      "account_deleted": 'Account Deleted',
      "reason": "Reason",
      "tell_us_reason": "Please tell us the reason",
      "are_u_want_logout": "Are you want to logout?",
      "search_currency": "Search currency...",
    },
    'bn_BN': {
      "edit": "সম্পাদনা করুন",
      "next": "পরবর্তী",
      "notification": "নোটিফিকেশন",
      "language": "ভাষা",
      "select_language": "ভাষা নির্বাচন করুন",
      "select_prefer_langugae": "আপনার পছন্দের ভাষা নির্বাচন করুন|",
      "continue": "চালিয়ে যান",
      "loading": "লোড হচ্ছে..",
      "error": "ত্রুটি",
      "server_busy":
      "অসুবিধার জন্য আমরা দুঃখিত, কিন্তু আমাদের সার্ভার বর্তমানে প্রচুর পরিমাণে ট্রাফিকের সম্মুখীন হচ্ছে৷ আপনার অ্যাকাউন্ট তৈরি করতে আমাদের নিয়মিত সাইন আপ প্রক্রিয়া ব্যবহার করুন. আপনার ধৈর্যের জন্য আপনাকে ধন্যবাদ.",
      "please_lo_first": "দয়া করে প্রথমে লগ ইন করুন!",
      "right_resarve_by": "দ্বারা সমস্ত অধিকার সংরক্ষিত",
      "continueText": "কন্টিনিউ",
      "success": "সাফল্য",
      //snackbar
      "warning": "সতর্কতা",
      //sign up
      "sign_up":"নিবন্ধন করুন",
      "sign_up_slogan":"নিবন্ধন পেতে আপনার নাম, ইমেল এবং পাসওয়ার্ড লিখুন",
      "name":"নাম",
      "phone":"ফোন",
      "password":"পাসওয়ার্ড",
      "or_sign_up_with":"অথবা সাইন আপ করুন",
      "agree_term":"আমি একমত",
      "and":"এবং",
      "already_have_account":"ইতিমধ্যে অ্যাকাউন্ট আছে?",
      "alReserveBy":"দ্বারা সমস্ত অধিকার সংরক্ষিত",
      //sign in
      "sign_in":"সাইন ইন করুন",
      "forgotPassword":"পাসওয়ার্ড ভুলে গেছেন",
      "or_sign_in_with":"অথবা দিয়ে সাইন ইন করুন",
      "dont_have_account":"অ্যাকাউন্ট নেই?",
      //home
      "hello": "হ্যালো",
      "im_your_assistant": "আমি আপনার অর্থ ব্যবস্থাপনা সহকারী",
      "this_week": "এই সপ্তাহ",
      "this_month": "এই মাস",
      "this_year": "এই বছর",
      "recent_transaction": "সাম্প্রতিক লেনদেন",
      "see_all": "সবগুলো দেখুন",
      "no_transaction_found": "কোন লেনদেন পাওয়া যায়নি!",
      //add transaction
      "transactions": "লেনদেন",
      "add_transaction": "লেনদেন যোগ করুন",
      "transaction_details": "লেনদেনের বিবরণ",
      "income": "আয়",
      "expense": "ব্যয়",
      "saving": "সংরক্ষণ",
      "insufficient_balance":
      "অপর্যাপ্ত টাকা. আপনাকে প্রথমে আয় যোগ করতে হবে।",
      "available_balance": "পর্যাপ্ত টাকা",
      "transaction_name": "লেনদেনের নাম",
      "purpose_of_transaction": "লেনদেনের উদ্দেশ্য",
      "enter_amount": "পরিমাণ লিখুন",
      "select_date": "তারিখ নির্বাচন করুন",
      "select_categgory": "বিভাগ নির্বাচন করুন",
      "add_calculate_amount": "গণনাকৃত পরিমাণ যোগ করুন",
      "select_a_category": "একটি বিভাগ নির্বাচন করুন",
      "please_enter_amount": "অনুগ্রহ করে লেনদেনের পরিমাণ লিখুন",
      "enter_transaction_name": "লেনদেনের নাম লিখুন",
      "save": "সংরক্ষণ",
      "write_note": "নোট লিখুন..",
      //attachment
      "browse_imge_here": "আপনার ইমেজ ব্রাউজ করুন",
      "supports": "সমর্থন করে",
      "choose_method": "আপনার পদ্ধতি চয়ন করুন",
      "max_2_size_allow": "অনুমোদিত সর্বাধিক ছবির আকার 2 MB",
      "you_denied_camera": "আপনি ক্যামেরা অ্যাক্সেস অস্বীকার করেছেন৷",
      //budget
      "your_budget": "আপনার বাজেট",
      "active": "সক্রিয়",
      "closed": "বন্ধ",
      "add_budget": "বাজেট যোগ করুন",
      "create_budget": "বাজেট তৈরি করুন",
      "budget_name": "বাজেটের নাম",
      "select_budget_period": "বাজেটের সময়কাল নির্বাচন করুন",
      "start_date": "শুরুর তারিখ",
      "end_date": "শেষ তারিখ",
      "warning_message":
      "আপনি যখন আপনার বাজেটের 50%, 80%,90% বাকিতে পৌঁছাবেন তখন আপনি একটি সতর্কতা পাবেন",
      "budget_overspend": "অতিরিক্ত ব্যয় করা বাজেট",
      "budget_overspend_message":
      "আপনি যখন আপনার বাজেটের 100% ছাড়িয়ে যাবেন তখন আপনি একটি সতর্কতা পাবেন",
      "enter_budget_name": "বাজেটের নাম লিখুন!",
      "enter_budget_period": "বাজেট সময়কাল নির্বাচন করুন!",
      "enter_start_date": 'শুরুর তারিখ চয়ন করুন!',
      "enter_end_date": 'অনুগ্রহ করে আনুমানিক শেষ তারিখ চয়ন করুন!',
      "available_budget": "উপলব্ধ বাজেট",
      "already_spend": "আপনি ইতিমধ্যে ব্যয়",
      "from": "থেকে",
      "recent_expense": "সাম্প্রতিক ব্যয়",
      "no_expense_history": "কোনো খরচের ইতিহাস নেই",
      "add_new_expense": "নতুন খরচ যোগ করুন",
      "cancel": "বাতিল করুন",
      "delete": "মুছে ফেলা",
      "add_record": "রেকর্ড যোগ করুন",
      "close_record": "বন্ধ রেকর্ড",
      //report
      "report": "রিপোর্ট",
      "download_pdf": "PDF ডাউনলোড করুন",
      "cash_in": "ক্যাশ ইন",
      "cash_out": "ক্যাশ আউট",
      "view_all": "সব দেখুন",
      "title": "শিরোনাম",
      "date": "তারিখ",
      "amount": "পরিমাণ",
      "statistic": "পরিসংখ্যান",
      "total_cash": "মোট নগদ",
      "total_cash_out": "মোট ক্যাশ আউট",
      "total_save": "মোট সংরক্ষণ",
      "balance": "ভারসাম্য",
      "budget": "বাজেট",
      "filter": "ছাঁকনি",
      "search": "অনুসন্ধান করুন",
      //goal
      "your_goal": "তোমার লক্ষ্যসমূহ",
      "goals": "গোল",
      "are_you_ambitious": "আপনি কি উচ্চাকাঙ্ক্ষী ব্যক্তি নন?",
      "paused": "বিরতি দেওয়া হয়েছে",
      "reached": "পৌঁছেছে",
      "new_goal": "নতুন লক্ষ্য",
      "not_found": "পাওয়া যায়নি",
      "add_goal": "লক্ষ্য যোগ করুন",
      "so_close_your_dream": "আপনার স্বপ্নের লক্ষ্যের এত কাছাকাছি!",
      "estimate_time_reach_goal": "লক্ষ্যে পৌঁছানোর আনুমানিক সময়",
      "add_money": "টাকা যোগ করুন",
      "pause_goal": "লক্ষ্য বিরতি",
      "reach_goal": "লক্ষ্যে পৌঁছেছে",
      "recent_added_money": "সাম্প্রতিক যোগ করা টাকা",
      "what_do_you_want_this_goal": "এই লক্ষ্যে আপনি কি চান?",
      "step": "ধাপ",
      "step_1_new_goal_message":
      "একটি লক্ষ্য নির্ধারণ করা এটি অর্জনের দিকে প্রথম পদক্ষেপ।",
      "goal_title": "গোলের শিরোনাম",
      "select_saving_period": "সেভিং পিরিয়ড নির্বাচন করুন",
      "select_reminder_period": "অনুস্মারক সময়কাল নির্বাচন করুন",
      "expected_maturity_date": "প্রত্যাশিত পরিপক্কতার তারিখ",
      "success_notify": "সাফল্য বিজ্ঞপ্তি",
      "success_notity_message":
      "আপনি যখন আপনার বাজেটের বাকি 50%, 80%, 90% পৌঁছে যাবেন তখন আপনি একটি সতর্কতা পাবেন।",
      "goal_overdue": "গোল ওভারডিউ",
      "goal_overdue_message":
      "আপনি একটি সতর্কতা পাবেন যখন আপনি সময়কালের মধ্যে একবারও টাকা সঞ্চয় করেননি।",
      "preview": "পূর্বরূপ",
      "recheck_your_goal": "আপনার লক্ষ্য পুনরায় পরীক্ষা করুন.",
      "previous": "আগে",
      "what_do_you_want_goal": "এই লক্ষ্যে আপনি কি চান?",
      "step_2_goal_message":
      "একটি লক্ষ্য নির্ধারণ করা এটি অর্জনের দিকে দ্বিতীয় ধাপ।",
      "create_goal": "লক্ষ্য তৈরি করুন",
      "weekly": "সাপ্তাহিক",
      "monthly": "মাসিক",
      "yearly": "বার্ষিক",
      "one_time": "একবার",
      //settings
      "settings": "সেটিংস",
      "settings_more": "সেটিংস এবং আরও",
      "general": "সাধারণ",
      "currency": "মুদ্রা",
      "application": "এপ্লিকেশন",
      "account_delete": "অ্যাকাউন্ট মুছে ফেলুন",
      "log_out": "প্রস্থান",
      "delete_message":
      "সতর্কতা: অ্যাকাউন্ট মুছে ফেলা অপরিবর্তনীয়৷ একবার মুছে ফেলা হলে, আপনার ডেটা পুনরুদ্ধার করা যাবে না৷ তথ্যের এই ক্ষতির জন্য কর্তৃপক্ষ দায়ী থাকবে না।",
      "fullName": "পুরো নাম",
      "email": "ইমেইল",
      "dob": "জন্ম তারিখ",
      "your_reason": "তোমার কারণ...",
      "account_deleted": 'অ্যাকাউন্ট মুছে ফেলা হয়েছে',
      "reason": "কারণ",
      "tell_us_reason": "আমাদের কারণ বলুন দয়া করে",
      "are_u_want_logout": "আপনি কি লগআউট করতে চান?",
      "search_currency": "মুদ্রা অনুসন্ধান করুন..",
    },
    'jp_JP': {
      "edit": "編集",
      "next": "次",
      "notification": "通知",
      "language": "言語",
      "select_language": "言語を選択する",
      "select_prefer_langugae": "ご希望の言語を選択してください。",
      "continue": "続く",
      "loading": "読み込み中..",
      "error": "エラー",
      "server_busy":
      "ご不便をおかけして申し訳ございませんが、現在サーバーに大量のトラフィックが発生しています。通常のサインアッププロセスを使用してアカウントを作成してください。お待ちいただいてありがとうございます",
      "please_lo_first": "まずはログインしてください！",
      "right_resarve_by": "すべての権利は次の者によって留保されます",
      "continueText": "続く",
      "success": "成功",
      //snackbar
      "warning": "警告",
      //sign up
      "sign_up":"サインアップ",
      "sign_up_slogan":"名前、メールアドレス、パスワードを入力して登録してください",
      "name":"名前",
      "phone":"電話",
      "password":"パスワード",
      "or_sign_up_with":"またはでサインアップしてください",
      "agree_term":"に同意します",
      "and":"そして",
      "already_have_account":"すでにアカウントをお持ちですか?",
      "alReserveBy":"すべての権利は次の者によって留保されます",
      //sign in
      "sign_in":"サインイン",
      "forgotPassword":"パスワードをお忘れですか",
      "or_sign_in_with":"または次の方法でサインインします",
      "dont_have_account":"アカウントをお持ちでない場合は、",
      //home
      "hello": "こんにちは",
      "im_your_assistant": "私はあなたのお金管理アシスタントです",
      "this_week": "今週",
      "this_month": "今月",
      "this_year": "今年",
      "recent_transaction": "最近の取引",
      "see_all": "すべてを見る",
      "no_transaction_found": "お得な情報が見つかりませんでした。",
      //add transaction'
      "transactions": "トランザクション",
      "add_transaction": "トランザクションの追加",
      "transaction_details": "取引詳細",
      "income": "所得",
      "expense": "料金",
      "saving": "節約",
      "insufficient_balance": "残高不足。まず収入を追加する必要があります。",
      "available_balance": "利用可能残高",
      "transaction_name": "トランザクション名",
      "purpose_of_transaction": "取引の目的",
      "enter_amount": "金額を入力してください",
      "select_date": "日付を選択してください",
      "select_categgory": "カテゴリを選択してください",
      "add_calculate_amount": "計算された金額を追加します",
      "select_a_category": "カテゴリを選んでください",
      "please_enter_amount": "取引金額を入力してください",
      "enter_transaction_name": "取引名を入力してください",
      "save": "保つ",
      "write_note": "記帳..",
      //attachment
      "browse_imge_here": "画像を閲覧する",
      "supports": "サポート",
      "choose_method": "方法を選択してください",
      "max_2_size_allow": "許可される最大画像サイズ 2 MB",
      "you_denied_camera": "カメラへのアクセスが拒否されました",
      //budget
      "your_budget": "ご予算",
      "active": "アクティブ",
      "closed": "閉まっている",
      "add_budget": "予算を追加",
      "create_budget": "予算の作成",
      "budget_name": "予算名",
      "select_budget_period": "予算期間の選択",
      "start_date": "開始日",
      "end_date": "終了日",
      "warning_message": "予算の残り 50%、80%、90% に達すると警告が表示されます",
      "budget_overspend": "予算超過",
      "budget_overspend_message": "予算の 100% を超えると警告が表示されます",
      "enter_budget_name": "予算名を入力してください。",
      "enter_budget_period": "予算期間を選択してください。",
      "enter_start_date": '開始日を選択してください。',
      "enter_end_date": '終了予定日を選択してください。',
      "available_budget": "利用可能な予算",
      "already_spend": "あなたはすでに費やしています",
      "from": "から",
      "recent_expense": "最近の出費",
      "no_expense_history": "経費履歴なし",
      "add_new_expense": "新しい経費を追加する",
      "cancel": "キャンセル",
      "delete": "消去",
      "add_record": "レコードの追加",
      "close_record": "記録を閉じる",
      //report
      "report": "報告",
      "download_pdf": "PDFをダウンロード",
      "cash_in": "現金で",
      "cash_out": "キャッシュアウト",
      "view_all": "すべて見る",
      "title": "タイトル",
      "date": "日付",
      "amount": "額",
      "statistic": "統計",
      "total_cash": "現金総額",
      "total_cash_out": "総キャッシュアウト",
      "total_save": "トータルセーブ",
      "balance": "バランス",
      "budget": "予算",
      "filter": "フィルター",
      "search": "検索",
      //goal
      "your_goal": "あなたの目標",
      "goals": "目標",
      "are_you_ambitious": "あなたは野心的な人ではありませんか？",
      "paused": "一時停止中",
      "reached": "到達しました",
      "new_goal": "新しい目標",
      "not_found": "見つかりません",
      "add_goal": "目標を追加",
      "so_close_your_dream": "あなたの夢の目標にとても近づいています!",
      "estimate_time_reach_goal": "目標到達までの推定時間",
      "add_money": "お金を追加する",
      "pause_goal": "ポーズゴール",
      "reach_goal": "目標を達成しました",
      "recent_added_money": "最近追加されたお金",
      "what_do_you_want_this_goal": "この目標に何を望んでいますか？",
      "step": "ステップ",
      "step_1_new_goal_message": "目標を設定することは、それを達成するための第一歩です。",
      "goal_title": "目標タイトル",
      "select_saving_period": "保存期間を選択",
      "select_reminder_period": "リマインダー期間の選択",
      "expected_maturity_date": "満期予定日",
      "success_notify": "成功通知",
      "success_notity_message": "予算の残り 50%、80%、90% に達すると、警告が表示されます。",
      "goal_overdue": "目標期限切れ",
      "goal_overdue_message": "期間の間に一度もお金を節約しなかった場合は、警告が表示されます。",
      "preview": "プレビュー",
      "recheck_your_goal": "目標を再確認してください。",
      "previous": "前の",
      "what_do_you_want_goal": "この目標に何を望んでいますか？",
      "step_2_goal_message": "目標を設定することは、それを達成するための第 2 ステップです。",
      "create_goal": "目標の作成",
      "weekly": "毎週",
      "monthly": "毎月",
      "yearly": "毎年",
      "one_time": "一度",
      //settings
      "settings": "設定",
      "settings_more": "設定など",
      "general": "一般的な",
      "currency": "通貨",
      "application": "応用",
      "account_delete": "アカウントの削除",
      "log_out": "ログアウト",
      "delete_message":
      "警告: アカウントの削除は元に戻せません。削除すると、データを復元することはできません。 当局はこのデータの損失について責任を負いません。",
      "fullName": "フルネーム",
      "email": "Eメール",
      "dob": "生年月日",
      "your_reason": "あなたの理由は...",
      "account_deleted": 'アカウントが削除されました',
      "reason": "理由",
      "tell_us_reason": "理由を教えてください",
      "are_u_want_logout": "ログアウトしますか?",
      "search_currency": "通貨を検索..",
    },
    'es_ES': {
      "edit": "Editar",
      "next": "Próximo",
      "notification": "Notificación",
      "language": "Idioma",
      "select_language": "Seleccione el idioma",
      "select_prefer_langugae": "Por favor seleccione su idioma preferido.",
      "continue": "Continuar",
      "loading": "Cargando..",
      "error": "el error",
      "server_busy":
      "Lamentamos las molestias, pero nuestro servidor actualmente está experimentando un gran volumen de tráfico. Utilice nuestro proceso de registro habitual para crear su cuenta. Gracias por su paciencia.",
      "please_lo_first": "Por favor ingresa primero!",
      "right_resarve_by": "Todos los derechos reservados por",
      "continueText": "Continuar",
      "success": "Éxito",
      //snackbar
      "warning": "advertencia",
      //sign up
      "sign_up":"Inscribirse",
      "sign_up_slogan":"Ingrese su nombre, correo electrónico y contraseña para registrarse",
      "name":"Nombre",
      "phone":"Teléfono",
      "password":"Contraseña",
      "or_sign_up_with":"o regístrate con",
      "agree_term":"Estoy de acuerdo con la",
      "and":"y",
      "already_have_account":"¿Ya tienes cuenta?",
      "alReserveBy":"Todos los derechos reservados por",
      //sign in
      "sign_in":"Iniciar sesión",
      "forgotPassword":"Has olvidado tu contraseña",
      "or_sign_in_with":"o inicia sesión con",
      "dont_have_account":"¿No tienes cuenta?",
      //home
      "hello": "Hola",
      "im_your_assistant": "Soy tu asistente de administración de dinero.",
      "this_week": "Esta semana",
      "this_month": "Este mes",
      "this_year": "Este año",
      "recent_transaction": "Transacciones Recientes",
      "see_all": "Ver todo",
      "no_transaction_found": "No se encontró ninguna transacción!",
      //add transaction
      "transactions": "transacción",
      "add_transaction": "Agregar transacción",
      "transaction_details": "Detalles de transacciones",
      "income": "Ingreso",
      "expense": "los gastos",
      "saving": "Ahorro",
      "insufficient_balance":
      "Saldo insuficiente. Primero debes sumar los ingresos.",
      "available_balance": "Saldo disponible",
      "transaction_name": "Nombre de la transacción",
      "purpose_of_transaction": "Propósito de la transacción",
      "enter_amount": "Introduce la cantidad",
      "select_date": "Seleccione fecha",
      "select_categgory": "Seleccione  categoría",
      "add_calculate_amount": "Agregar cantidad calculada",
      "select_a_category": "Seleccione una categoría",
      "please_enter_amount": "Por favor ingrese el monto de la transacción",
      "enter_transaction_name": "Ingrese el nombre de la transacción",
      "save": "Ahorrar",
      "write_note": "Toma nota..",
      //attachment
      "browse_imge_here": "Explora tu imagen",
      "supports": "Soportes",
      "choose_method": "Elige tu método",
      "max_2_size_allow": "Tamaño máximo de imagen permitido 2 MB",
      "you_denied_camera": "Has negado el acceso a la cámara",
      //budget
      "your_budget": "Su presupuesto",
      "active": "Activo",
      "closed": "Cerrado",
      "add_budget": "Agregar presupuesto",
      "create_budget": "Crear presupuesto",
      "budget_name": "Nombre del presupuesto",
      "select_budget_period": "Seleccione el período presupuestario",
      "start_date": "Fecha de inicio",
      "end_date": "Fecha final",
      "warning_message":
      "Recibirás una advertencia cuando hayas alcanzado el 50 %, 80 % o 90 % restante de tu presupuesto.",
      "budget_overspend": "Presupuesto gastado en exceso",
      "budget_overspend_message":
      "Recibirás una advertencia cuando hayas superado el 100% de tu presupuesto.",
      "enter_budget_name": "¡Por favor ingrese el nombre del presupuesto!",
      "enter_budget_period": "¡Seleccione el período presupuestario!",
      "enter_start_date": '¡Elija la fecha de inicio!',
      "enter_end_date": '¡Elija la fecha de finalización estimada!',
      "available_budget": "Presupuesto disponible",
      "already_spend": "ya gastas",
      "from": "de",
      "recent_expense": "Gasto reciente",
      "no_expense_history": "Sin historial de gastos",
      "add_new_expense": "Agregar nuevo gasto",
      "cancel": "Cancelar",
      "delete": "Borrar",
      "add_record": "Agregar registro",
      "close_record": "Cerrar registro",
      //report
      "report": "Informe",
      "download_pdf": "Descargar PDF",
      "cash_in": "Dinero en efectivo en",
      "cash_out": "Retiro de efectivo",
      "view_all": "Ver todo",
      "title": "Título",
      "date": "Fecha",
      "amount": "Cantidad",
      "statistic": "Estadística",
      "total_cash": "Efectivo Total",
      "total_cash_out": "Retiro total de efectivo",
      "total_save": "Ahorro Total",
      "balance": "Balance",
      "budget": "Presupuesto",
      "filter": "Filtrar",
      "search": "Buscar",
      //goal
      "your_goal": "Tus metas",
      "goals": "Objetivos",
      "are_you_ambitious": "¿No eres una persona ambiciosa?",
      "paused": "En pausa",
      "reached": "Alcanzó",
      "new_goal": "Nuevo gol",
      "not_found": "No encontrado",
      "add_goal": "Agregar objetivo",
      "so_close_your_dream": "¡Tan cerca de la meta de tus sueños!",
      "estimate_time_reach_goal": "Tiempo estimado para alcanzar la meta",
      "add_money": "Agregar dinero",
      "pause_goal": "Pausar objetivo",
      "reach_goal": "Meta alcanzada",
      "recent_added_money": "Dinero agregado recientemente",
      "what_do_you_want_this_goal": "¿Qué quieres en este objetivo?",
      "step": "Paso",
      "step_1_new_goal_message":
      "Establecer una meta es el primer paso para lograrla.",
      "goal_title": "Título del objetivo",
      "select_saving_period": "Seleccione el período de ahorro",
      "select_reminder_period": "Seleccionar período de recordatorio",
      "expected_maturity_date": "Fecha de vencimiento prevista",
      "success_notify": "Notificar éxito",
      "success_notity_message":
      "Recibirá una advertencia cuando haya alcanzado el 50%, 80%, 90% restante de su presupuesto.",
      "goal_overdue": "Objetivo vencido",
      "goal_overdue_message":
      "Recibirá una advertencia cuando no haya ahorrado dinero una vez entre la duración.",
      "preview": "Avance",
      "recheck_your_goal": "Vuelve a comprobar tu objetivo.",
      "previous": "Previo",
      "what_do_you_want_goal": "¿Qué quieres en este objetivo?",
      "step_2_goal_message":
      "Establecer una meta es el segundo paso para lograrla.",
      "create_goal": "Crear objetivo",
      "weekly": "Semanalmente",
      "monthly": "Mensual",
      "yearly": "Anual",
      "one_time": "Una vez",
      //settings
      "settings": "Ajustes",
      "settings_more": "Configuración y más",
      "general": "General",
      "currency": "Divisa",
      "application": "Solicitud",
      "account_delete": "Eliminar cuenta",
      "log_out": "Cerrar sesión",
      "delete_message":
      "Advertencia: la eliminación de la cuenta es irreversible. Una vez eliminada, sus datos no se pueden recuperar. La Autoridad no será responsable de esta pérdida de datos.",
      "fullName": "Nombre completo",
      "email": "Correo electrónico",
      "dob": "Fecha de nacimiento",
      "your_reason": "Tu razón...",
      "account_deleted": 'Cuenta borrada',
      "reason": "Razón",
      "tell_us_reason": "Por favor dinos el motivo",
      "are_u_want_logout": "¿Quieres cerrar sesión?",
      "search_currency": "Buscar moneda..",
    },
    'fr_FR': {
      "edit": "Modifier",
      "next": "Suivant",
      "notification": "Notification",
      "language": "Langue",
      "select_language": "Choisir la langue",
      "select_prefer_langugae":
      "Veuillez sélectionner votre langue préférée.",
      "continue": "Continuer",
      "loading": "Chargement..",
      "error": "Erreur",
      "server_busy":
      "Nous nous excusons pour la gêne occasionnée, mais notre serveur connaît actuellement un volume de trafic élevé. Veuillez utiliser notre processus d'inscription habituel pour créer votre compte. Merci pour votre patience.",
      "please_lo_first": "S'il vous plait Connectez-vous d'abord!",
      "right_resarve_by": "Tous droits réservés par",
      "continueText": "Continuer",
      "success": "Succès",
      //snackbar
      "warning": "avertissement",
      //sign up
      "sign_up":"S'inscrire",
      "sign_up_slogan":"Entrez votre nom, email et mot de passe pour vous inscrire",
      "name":"Nom",
      "phone":"Téléphone",
      "password":"Mot de passe",
      "or_sign_up_with":"ou inscrivez-vous avec",
      "agree_term":"je suis d'accord avec le",
      "and":"et",
      "already_have_account":"Vous avez déjà un compte ?",
      "alReserveBy":"Tous droits réservés par",
      //sign in
      "sign_in":"Se connecter",
      "forgotPassword":"Mot de passe oublié",
      "or_sign_in_with":"ou connectez-vous avec",
      "dont_have_account":"Vous n'avez pas de compte ?",

      //home
      "hello": "Bonjour",
      "im_your_assistant": "Je suis votre assistante en gestion financière",
      "this_week": "Cette semaine",
      "this_month": "Ce mois-ci",
      "this_year": "Cette année",
      "recent_transaction": "transactions récentes",
      "see_all": "Tout voir",
      "no_transaction_found": "Aucune transaction trouvée!",
      //add transaction
      "transactions": "transaction",
      "add_transaction": "Ajouter une transaction",
      "transaction_details": "Détails des transactions",
      "income": "Revenu",
      "expense": "les frais",
      "saving": "salvateur",
      "insufficient_balance":
      "Solde insuffisant. Vous devez d’abord ajouter des revenus.",
      "available_balance": "Solde disponible",
      "transaction_name": "Nom de la transaction",
      "purpose_of_transaction": "Objet de l'opération",
      "enter_amount": "Entrez le montant",
      "select_date": "Sélectionnez une date",
      "select_categgory": "Choisissez une catégorie",
      "add_calculate_amount": "Ajoutez le montant calculé",
      "select_a_category": "Choisir une catégorie",
      "please_enter_amount": "Veuillez saisir le montant de la transaction",
      "enter_transaction_name": "Entrez le nom de la transaction",
      "save": "économiser",
      "write_note": "Écrire une note..",
      //attachment
      "browse_imge_here": "Parcourez votre image",
      "supports": "Les soutiens",
      "choose_method": "Choisissez votre méthode",
      "max_2_size_allow": "Taille d'image maximale autorisée 2 Mo",
      "you_denied_camera": "Vous avez refusé l'accès à la caméra",
      //budget
      "your_budget": "Ton budget",
      "active": "Actif",
      "closed": "Fermé",
      "add_budget": "Ajouter un budget",
      "create_budget": "Créer un budget",
      "budget_name": "Nom du budget",
      "select_budget_period": "Sélectionnez la période budgétaire",
      "start_date": "Date de début",
      "end_date": "Date de fin",
      "warning_message":
      "Vous recevrez un avertissement lorsqu'il vous restera 50 %, 80 % ou 90 % de votre budget.",
      "budget_overspend": "Budget dépassé",
      "budget_overspend_message":
      "Vous recevrez un avertissement lorsque vous aurez dépassé 100 % de votre budget",
      "enter_budget_name": "Veuillez saisir le nom du budget !",
      "enter_budget_period":
      "Veuillez sélectionner la période budgétaire !",
      "enter_start_date": 'Veuillez choisir la date de début !',
      "enter_end_date": 'Veuillez choisir la date de fin estimée !',
      "available_budget": "Budget disponible",
      "already_spend": "Vous dépensez déjà",
      "from": "depuis",
      "recent_expense": "Dépense récente",
      "no_expense_history": "Aucun historique de dépenses",
      "add_new_expense": "Ajouter une nouvelle dépense",
      "cancel": "Annuler",
      "delete": "Supprimer",
      "add_record": "Ajouter un enregistrement",
      "close_record": "Fermer l'enregistrement",
      //report
      "report": "Rapport",
      "download_pdf": "Télécharger le PDF",
      "cash_in": "Encaisser",
      "cash_out": "Encaissement",
      "view_all": "Voir tout",
      "title": "Titre",
      "date": "Date",
      "amount": "Montant",
      "statistic": "Statistique",
      "total_cash": "Trésorerie totale",
      "total_cash_out": "Total des retraits",
      "total_save": "Économie totale",
      "balance": "Équilibre",
      "budget": "Budget",
      "filter": "Filtre",
      "search": "Recherche",
      //goal
      "your_goal": "Tes objectifs",
      "goals": "Objectifs",
      "are_you_ambitious": "N'êtes-vous pas une personne ambitieuse ?",
      "paused": "En pause",
      "reached": "Atteint",
      "new_goal": "Nouveau but",
      "not_found": "Pas trouvé",
      "add_goal": "Ajouter un objectif",
      "so_close_your_dream": "Si proche de l’objectif de vos rêves !",
      "estimate_time_reach_goal": "Temps estimé pour atteindre l'objectif",
      "add_money": "Ajouter de l'argent",
      "pause_goal": "Suspendre l'objectif",
      "reach_goal": "Objectif atteint",
      "recent_added_money": "Argent ajouté récemment",
      "what_do_you_want_this_goal": "Que veux-tu dans cet objectif ?",
      "step": "Étape",
      "step_1_new_goal_message":
      "Se fixer un objectif est la première étape pour l'atteindre.",
      "goal_title": "Titre de l'objectif",
      "select_saving_period": "Sélectionnez Période d'épargne",
      "select_reminder_period": "Sélectionnez la période de rappel",
      "expected_maturity_date": "Date d'échéance prévue",
      "success_notify": "Notification de réussite",
      "success_notity_message":
      "Vous recevrez un avertissement lorsque vous aurez atteint 50 %, 80 %, 90 % restant de votre budget.",
      "goal_overdue": "Objectif en retard",
      "goal_overdue_message":
      "Vous recevrez un avertissement lorsque vous n'aurez pas économisé d'argent une fois entre la durée.",
      "preview": "Aperçu",
      "recheck_your_goal": "Revérifiez votre objectif.",
      "previous": "Précédent",
      "what_do_you_want_goal": "Que veux-tu dans cet objectif ?",
      "step_2_goal_message":
      "Se fixer un objectif est la deuxième étape pour l'atteindre.",
      "create_goal": "Créer un objectif",
      "weekly": "Hebdomadaire",
      "monthly": "Mensuel",
      "yearly": "Annuel",
      "one_time": "Une fois",
      //settings
      "settings": "Paramètres",
      "settings_more": "Paramètres et plus",
      "general": "Général",
      "currency": "Devise",
      "application": "Application",
      "account_delete": "Supprimer le compte",
      "log_out": "Se déconnecter",
      "delete_message":
      "Attention : la suppression du compte est irréversible. Une fois supprimées, vos données ne peuvent plus être récupérées. L'autorité ne sera pas responsable de cette perte de données.",
      "fullName": "Nom et prénom",
      "email": "E-mail",
      "dob": "Date de naissance",
      "your_reason": "Votre raison...",
      "account_deleted": 'Compte supprimé',
      "reason": "Raison",
      "tell_us_reason": "S'il vous plaît dites-nous la raison",
      "are_u_want_logout": "Voulez-vous vous déconnecter ?",
      "search_currency": "Rechercher une devise..",
    },
    'hi_HI': {
      "edit": "संपादन करना",
      "next": "अगला",
      "notification": "अधिसूचना",
      "language": "भाषा",
      "select_language": "भाषा चुने",
      "select_prefer_langugae": "कृपया अपनी पसंदीदा भाषा चुनें.",
      "continue": "जारी रखना",
      "loading": "लोड हो रहा है..",
      "error": "गलती",
      "server_busy":
      "असुविधा के लिए हमें खेद है, लेकिन हमारा सर्वर इस समय भारी मात्रा में ट्रैफ़िक का अनुभव कर रहा है। कृपया अपना खाता बनाने के लिए हमारी नियमित साइन-अप प्रक्रिया का उपयोग करें। आपके धैर्य के लिए धन्यवाद।",
      "please_lo_first": "कृपया पहले लौग इन करें!",
      "right_resarve_by": "सर्वाधिकार सुरक्षित",
      "continueText": "जारी रखना",
      "success": "सफलता",
      //snackbar
      "warning": "चेतावनी",
      //sign up
      "sign_up":"साइन अप करें",
      "sign_up_slogan":"रजिस्टर करने के लिए अपना नाम, ईमेल और पासवर्ड दर्ज करें",
      "name":"नाम",
      "phone":"फ़ोन",
      "password":"पासवर्ड",
      "or_sign_up_with":"या इसके साथ साइन अप करें",
      "agree_term":"मैं करने के लिए सहमत हूं",
      "and":"और",
      "already_have_account":"पहले से ही खाता है?",
      "alReserveBy":"सर्वाधिकार सुरक्षित",
      //sign in
      "sign_in":"दाखिल करना",
      "forgotPassword":"पासवर्ड भूल गए",
      "or_sign_in_with":"या इसके साथ साइन इन करें",
      "dont_have_account":"खाता नहीं है?",
      //home
      "hello": "नमस्ते",
      "im_your_assistant": "मैं आपका धन प्रबंधन सहायक हूं",
      "this_week": "इस सप्ताह",
      "this_month": "इस महीने",
      "this_year": "इस साल",
      "recent_transaction": "हाल ही के लेनदेन",
      "see_all": "सभी देखें",
      "no_transaction_found": "कोई परिणाम नहीं मिले!",
      //add transaction
      "transactions": "लेन-देन",
      "add_transaction": "लेन-देन जोड़ें",
      "transaction_details": "लेन-देन विवरण",
      "income": "आय",
      "expense": "व्यय",
      "saving": "बचत",
      "insufficient_balance":
      "अपर्याप्त शेषराशि। सबसे पहले आपको आय जोड़नी होगी.",
      "available_balance": "उपलब्ध शेष राशि",
      "transaction_name": "लेन-देन का नाम",
      "purpose_of_transaction": "लेन-देन का उद्देश्य",
      "enter_amount": "राशि डालें",
      "select_date": "तारीख़ चुनें",
      "select_categgory": "श्रेणी चुनना",
      "add_calculate_amount": "गणना की गई राशि जोड़ें",
      "select_a_category": "एक श्रेणी चुनें",
      "please_enter_amount": "कृपया लेनदेन राशि दर्ज करें",
      "enter_transaction_name": "लेन-देन का नाम दर्ज करें",
      "save": "बचाना",
      "write_note": "एक लेख लिखो..",
      //attachment
      "browse_imge_here": "अपनी छवि ब्राउज़ करें",
      "supports": "समर्थन",
      "choose_method": "अपना तरीका चुनें",
      "max_2_size_allow": "अनुमत अधिकतम छवि आकार 2 एमबी",
      "you_denied_camera": "आपने कैमरे तक पहुंच से इनकार कर दिया",
      //budget
      "your_budget": "आपका बजट",
      "active": "सक्रिय",
      "closed": "बंद किया हुआ",
      "add_budget": "बजट जोड़ें",
      "create_budget": "बजट बनाएं",
      "budget_name": "बजट का नाम",
      "select_budget_period": "बजट अवधि चुनें",
      "start_date": "आरंभ करने की तिथि",
      "end_date": "अंतिम तिथि",
      "warning_message":
      "जब आप अपने बजट के 50%, 80%, 90% तक पहुंच जाएंगे तो आपको एक चेतावनी मिलेगी",
      "budget_overspend": "बजट जरूरत से ज्यादा खर्च",
      "budget_overspend_message":
      "जब आपका बजट 100% से अधिक हो जाएगा तो आपको एक चेतावनी मिलेगी",
      "enter_budget_name": "कृपया बजट नाम दर्ज करें!",
      "enter_budget_period": "कृपया बजट अवधि चुनें!",
      "enter_start_date": 'कृपया आरंभ तिथि चुनें!',
      "enter_end_date": 'कृपया अनुमानित समाप्ति तिथि चुनें!',
      "available_budget": "उपलब्ध बजट",
      "already_spend": "आप पहले ही खर्च कर चुके हैं",
      "from": "से",
      "recent_expense": "हाल का खर्च",
      "no_expense_history": "कोई व्यय इतिहास नहीं",
      "add_new_expense": "नया व्यय जोड़ें",
      "cancel": "रद्द करना",
      "delete": "मिटाना",
      "add_record": "रिकॉर्ड जोड़ें",
      "close_record": "रिकॉर्ड बंद करें",
      //report
      "report": "प्रतिवेदन",
      "download_pdf": "डाउनलोड पीडीऍफ़",
      "cash_in": "नकद में",
      "cash_out": "नकदी निकलना",
      "view_all": "सभी को देखें",
      "title": "शीर्षक",
      "date": "तारीख",
      "amount": "मात्रा",
      "statistic": "सांख्यिकीय",
      "total_cash": "कुल नकद",
      "total_cash_out": "कुल नकद निकासी",
      "total_save": "कुल बचत",
      "balance": "संतुलन",
      "budget": "बजट",
      "filter": "फ़िल्टर",
      "search": "खोज",
      //goal
      "your_goal": "तुम्हारे लक्ष्य",
      "goals": "लक्ष्य",
      "are_you_ambitious": "क्या आप महत्वाकांक्षी व्यक्ति नहीं हैं?",
      "paused": "रोके गए",
      "reached": "पहुँच गया",
      "new_goal": "नया लक्ष्य",
      "not_found": "नहीं मिला",
      "add_goal": "लक्ष्य जोड़ें",
      "so_close_your_dream": "अपने सपनों के लक्ष्य के बहुत करीब!",
      "estimate_time_reach_goal": "लक्ष्य तक पहुंचने का अनुमानित समय",
      "add_money": "पैसे जोड़ें",
      "pause_goal": "लक्ष्य रोकें",
      "reach_goal": "लक्ष्य तक पहुंच गया",
      "recent_added_money": "हाल ही में जोड़ा गया पैसा",
      "what_do_you_want_this_goal": "आप इस लक्ष्य में क्या चाहते हैं?",
      "step": "कदम",
      "step_1_new_goal_message":
      "लक्ष्य निर्धारित करना उसे प्राप्त करने की दिशा में पहला कदम है।",
      "goal_title": "लक्ष्य शीर्षक",
      "select_saving_period": "बचत अवधि का चयन करें",
      "select_reminder_period": "अनुस्मारक अवधि का चयन करें",
      "expected_maturity_date": "अपेक्षित परिपक्वता तिथि",
      "success_notify": "सफलता की सूचना",
      "success_notity_message":
      "जब आप अपने बजट के 50%, 80%, 90% तक पहुंच जाएंगे तो आपको एक चेतावनी मिलेगी।",
      "goal_overdue": "लक्ष्य अतिदेय",
      "goal_overdue_message":
      "जब आपने अवधि के बीच एक बार पैसे नहीं बचाए तो आपको चेतावनी मिलेगी।",
      "preview": "पूर्व दर्शन",
      "recheck_your_goal": "अपने लक्ष्य को दोबारा जांचें.",
      "previous": "Previous",
      "what_do_you_want_goal": "आप इस लक्ष्य में क्या चाहते हैं?",
      "step_2_goal_message":
      "लक्ष्य निर्धारित करना उसे प्राप्त करने की दिशा में दूसरा कदम है।",
      "create_goal": "लक्ष्य बनाएं",
      "weekly": "साप्ताहिक",
      "monthly": "महीने के",
      "yearly": "सालाना",
      "one_time": "वन टाइम",
      //settings
      "settings": "समायोजन",
      "settings_more": "सेटिंग्स और अधिक",
      "general": "सामान्य",
      "currency": "मुद्रा",
      "application": "आवेदन",
      "account_delete": "खाता हटाएँ",
      "log_out": "लॉग आउट",
      "delete_message":
      "चेतावनी: खाता हटाना अपरिवर्तनीय है। एक बार हटा दिए जाने पर, आपका डेटा पुनर्प्राप्त नहीं किया जा सकता। डेटा की इस हानि के लिए प्राधिकरण जिम्मेदार नहीं होगा।",
      "fullName": "पूरा नाम",
      "email": "ईमेल",
      "dob": "जन्म की तारीख",
      "your_reason": "तुम्हारा कारण...",
      "account_deleted": 'खाता हटा दिया गया',
      "reason": "कारण",
      "tell_us_reason": "कृपया हमें कारण बताएं",
      "are_u_want_logout": "क्या आप लॉगआउट करना चाहते हैं?",
      "search_currency": "मुद्रा खोजें..",
    },
    'ar_AR': {
      "edit": "يحرر",
      "next": "التالي",
      "notification": "الإخطار",
      "language": "لغة",
      "select_language": "اختار اللغة",
      "select_prefer_langugae": "الرجاء تحديد لغتك المفضلة.",
      "continue": "يكمل",
      "loading": "تحميل",
      "error": "خطأ",
      "server_busy":
      "نعتذر عن الإزعاج، لكن خادمنا يواجه حاليًا حجمًا كبيرًا من حركة المرور. يرجى استخدام عملية التسجيل المعتادة لدينا لإنشاء حسابك. شكرا لك على صبرك.",
      "please_lo_first": "الرجاء تسجيل الدخول أولا!",
      "right_resarve_by": "جميع الحقوق محفوظة بواسطة",
      "continueText": "واصل",
      "success": "نجاح",
      //snackbar
      "warning": "تحذير",
      //sign up
      "sign_up":"اشتراك",
      "sign_up_slogan":"أدخل اسمك والبريد الإلكتروني وكلمة المرور للحصول على التسجيل",
      "name":"اسم",
      "phone":"هاتف",
      "password":"كلمة المرور",
      "or_sign_up_with":"أو قم بالتسجيل مع",
      "agree_term":"أنا أوافق على",
      "and":"و",
      "already_have_account":"هل لديك حساب بالفعل؟",
      "alReserveBy":"جميع الحقوق محفوظة بواسطة",
      //sign in
      "sign_in":"تسجيل الدخول",
      "forgotPassword":"هل نسيت كلمة السر",
      "or_sign_in_with":"أو قم بتسجيل الدخول باستخدام",
      "dont_have_account":"ليس لديك حساب؟",
      //home
      "hello": "مرحبًا",
      "im_your_assistant": "أنا مساعد إدارة أموالك",
      "this_week": ".هذا الاسبوع",
      "this_month": "هذا الشهر",
      "this_year": "هذا العام",
      "recent_transaction": "التحويلات الأخيرة",
      "see_all": "عرض الكل",
      "no_transaction_found": "لم يتم العثور على أي معاملة",
      //add transaction
      "transactions": "المعامل",
      "add_transaction": "إضافة المعاملة",
      "transaction_details": "تفاصيل المعاملات",
      "income": "يدخل",
      "expense": "نفقة",
      "saving": "ادخار",
      "insufficient_balance": "رصيد غير كاف. أولا تحتاج إلى إضافة الدخل.",
      "available_balance": "الرصيد المتوفر",
      "transaction_name": "اسم المعاملة",
      "purpose_of_transaction": "الغرض من الصفقة",
      "enter_amount": "أدخل المبلغ",
      "select_date": "حدد تاريخا",
      "select_categgory": "اختر الفئة",
      "add_calculate_amount": "أضف المبلغ المحسوب",
      "select_a_category": "اختر فئة",
      "please_enter_amount": "الرجاء إدخال مبلغ المعاملة",
      "enter_transaction_name": "أدخل اسم المعاملة",
      "save": "وفر",
      "write_note": "اكتب ملا حظة",
      //attachment
      "browse_imge_here": "تصفح صورتك",
      "supports": "يدعم",
      "choose_method": "اختر طريقتك",
      "max_2_size_allow":
      "الحد الأقصى لحجم الصورة المسموح به هو 2 ميجابايت",
      "you_denied_camera": "لقد رفضت الوصول إلى الكاميرا",
      //budget
      "your_budget": "ميزانيتك",
      "active": "نشيط",
      "closed": "مغلق",
      "add_budget": "أضف الميزانية",
      "create_budget": "إنشاء الميزانية",
      "budget_name": "اسم الميزانية",
      "select_budget_period": "حدد فترة الميزانية",
      "start_date": "تاريخ البدء",
      "end_date": "تاريخ الانتهاء",
      "warning_message":
      "ستتلقى تحذيرًا عندما تصل إلى 50%، 80%، 90% من ميزانيتك",
      "budget_overspend": "تجاوزت الميزانية",
      "budget_overspend_message":
      "ستتلقى تحذيرًا عندما تتجاوز 100% من ميزانيتك",
      "enter_budget_name": "الرجاء إدخال اسم الميزانية!",
      "enter_budget_period": "الرجاء تحديد فترة الميزانية!",
      "enter_start_date": 'الرجاء اختيار تاريخ البدء!',
      "enter_end_date": 'الرجاء اختيار تاريخ الانتهاء المقدر!',
      "available_budget": "الميزانية المتاحة",
      "already_spend": "أنت تنفق بالفعل",
      "from": "من",
      "recent_expense": "النفقات الأخيرة",
      "no_expense_history": "لا يوجد تاريخ النفقات",
      "add_new_expense": "إضافة حساب جديد",
      "cancel": "يلغي",
      "delete": "يمسح",
      "add_record": "إضافة سجل",
      "close_record": "إغلاق السجل",
      //report
      "report": "تقرير",
      "download_pdf": "تحميل PDF",
      "cash_in": "التدفقات النقدية الداخلة",
      "cash_out": "المصروفات",
      "view_all": "عرض الكل",
      "title": "عنوان",
      "date": "تاريخ",
      "amount": "كمية",
      "statistic": "إحصائية",
      "total_cash": "مجموع المبالغ النقدية",
      "total_cash_out": "إجمالي النقدية الخارجة",
      "total_save": "إجمالي الحفظ",
      "balance": "توازن",
      "budget": "ميزانية",
      "filter": "منقي",
      "search": "يبحث",
      //goal
      "your_goal": "أهدافك",
      "goals": "الأهداف",
      "are_you_ambitious": "هل أنت لست شخص طموح؟",
      "paused": "متوقف مؤقتًا",
      "reached": "وصل",
      "new_goal": "الهدف الجديد",
      "not_found": "غير معثور عليه",
      "add_goal": "أضف هدف",
      "so_close_your_dream": "قريب جدًا من هدف أحلامك!",
      "estimate_time_reach_goal": "الوقت المقدر للوصول إلى الهدف",
      "add_money": "إضافة المال",
      "pause_goal": "وقفة الهدف",
      "reach_goal": "وصلت إلى الهدف",
      "recent_added_money": "الأموال المضافة الأخيرة",
      "what_do_you_want_this_goal": "ماذا تريد في هذا الهدف؟",
      "step": "خطوة",
      "step_1_new_goal_message": "تحديد الهدف هو الخطوة الأولى نحو تحقيقه.",
      "goal_title": "عنوان الهدف",
      "select_saving_period": "حدد فترة الحفظ",
      "select_reminder_period": "حدد فترة التذكير",
      "expected_maturity_date": "تاريخ الاستحقاق المتوقع",
      "success_notify": "إخطار النجاح",
      "success_notity_message":
      "ستتلقى تحذيرًا عندما تصل إلى 50%، 80%، 90% من ميزانيتك.",
      "goal_overdue": "هدف متأخر",
      "goal_overdue_message":
      "سوف تحصل على تحذير عندما لا تقوم بتوفير المال مرة واحدة بين المدة.",
      "preview": "معاينة",
      "recheck_your_goal": "أعد التحقق من هدفك.",
      "previous": "سابق",
      "what_do_you_want_goal": "ماذا تريد في هذا الهدف؟",
      "step_2_goal_message": "تحديد الهدف هو الخطوة الثانية نحو تحقيقه.",
      "create_goal": "إنشاء الهدف",
      "weekly": "أسبوعي",
      "monthly": "شهريا",
      "yearly": "سنوي",
      "one_time": "مره واحده",
      //settings
      "settings": "إعدادات",
      "settings_more": "الإعدادات والمزيد",
      "general": "عام",
      "currency": "عملة",
      "application": "طلب",
      "account_delete": "حذف الحساب",
      "log_out": "تسجيل خروج",
      "delete_message":
      "تحذير: لا يمكن التراجع عن حذف الحساب. بمجرد حذفه، لا يمكن استعادة بياناتك. لن تكون الهيئة مسؤولة عن فقدان البيانات.",
      "fullName": "الاسم الكامل",
      "email": "بريد إلكتروني",
      "dob": "تاريخ الميلاد",
      "your_reason": "سببك...",
      "account_deleted": 'تم حذف الحساب',
      "reason": "سبب",
      "tell_us_reason": "من فضلك قل لنا السبب",
      "are_u_want_logout": "هل تريد تسجيل الخروج؟",
      "search_currency": "بحث عن العملة..",
    },
  };
}
